import { StyleSheet } from "react-native";
import Colors from "../globals/colors";
import Fonts from "../globals/fonts";
import Sizes from "./Sizes";
import Constants from "./Constants";
export default StyleSheet.create({
  bottomTabSelectedView: {
    backgroundColor: Colors.Main,
    justifyContent: "center",
    borderRadius: 8,
    alignItems: "center",
    flexDirection: "row",
    padding: 10,
    margin: 15,
    marginBottom: 10,
    shadowColor: Colors.Black_000000,
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    elevation: 5,
  },
  bottomTabUnSelectedView: {
    backgroundColor: Colors.cardColor,
    justifyContent: "center",
    borderRadius: 8,
    alignItems: "center",
    flexDirection: "row",
    padding: 10,
    margin: 15,
    marginBottom: 10,
  },
  bottomTab: {
    paddingTop: 5,
    paddingBottom: 5,
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  bottomUnTab: {
    paddingTop: 5,
    paddingBottom: 5,
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  bottomTabTextStyle: {
    marginLeft: 5,
    paddingTop: 5,
    fontWeight: "bold",
    paddingBottom: 5,
    alignSelf: "center",
    textAlign: "center",
    fontSize: Sizes.Regular,
    color: Colors.White_FFFFFF,
  },

  bottomUnTabTextStyle: {
    // marginLeft: 5,
    paddingTop: 3,
    // paddingBottom: 5,
    alignSelf: "center",
    textAlign: "center",
    fontSize: Sizes.Small,
    color: "#9E9E9E",
  },

  menuBack: {
    position: "absolute",
    flex: 1,
    marginTop: Constants.isIos ? 40 : 5,
    height: 40,
    width: 45,
    marginLeft: 20,
    backgroundColor: Colors.White_FFFFFF,
    shadowColor: Colors.Black_000000,
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    elevation: 5,
    borderRadius: 5,
    flexDirection: "row",
    paddingRight: 16,
  },
  menuContianr: {
    flex: 1,
    height: 40,
    justifyContent: "center",
    backgroundColor: Colors.White_FFFFFF,
    paddingLeft: 10,
    borderRadius: 5,
  },
  tabBack: {
    position: "absolute",
    flex: 1,
    // marginTop: Constants.isIos ? 10 : 5,
    height: 40,
    backgroundColor: Colors.White_FFFFFF,
    shadowColor: Colors.Black_000000,
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    elevation: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    paddingRight: 16,
    alignSelf: "center",
  },
  tabTextStyle: {
    fontSize: Sizes.Large,
    fontWeight: "400",
    marginLeft: 16,
    color: Colors.Black_000000,
  },
  tabTextStyleBold: {
    fontSize: Sizes.Large,
    fontWeight: "800",
    marginLeft: 16,
    color: Colors.Main,
  },
  line: {
    marginLeft: 16,
    height: 20,
    width: 1,
    backgroundColor: Colors.Black_000000,
  },
  menu: {
    width: 25,
    height: 25,
    resizeMode: "contain",
  },
  sortBack: {
    position: "absolute",
    flex: 1,
    height: 40,
    width: 45,
    // marginTop: Constants.isIos ? 40 : 5,
    marginLeft: Sizes.ScreenWidth - 70,
    backgroundColor: Colors.White_FFFFFF,
    shadowColor: Colors.Black_000000,
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    elevation: 5,
    borderRadius: 5,
    flexDirection: "row",
    paddingRight: 16,
  },
  sortContianr: {
    flex: 1,
    height: 40,
    justifyContent: "center",
    backgroundColor: Colors.White_FFFFFF,
    paddingLeft: 10,
    borderRadius: 5,
  },
  sort: {
    width: 25,
    height: 25,
    resizeMode: "contain",
    alignSelf: "center",
  },
  centerView: {
    // marginLeft: Platform.OS == 'android' ? Sizes.ScreenWidth*0.02 : 0,
    width: Sizes.ScreenWidth,
    marginLeft: -20,
    // marginLeft: Constants.isIos ? -40 : 0,
    justifyContent: "center",
    // width:Sizes.ScreenWidth-200,
    alignItems: "center",
    flex: 1,
    // width: Constants.isIos ? Sizes.ScreenWidth - 160 : null,
  },

  centerView1: {
    marginLeft: Platform.OS == "android" ? Sizes.ScreenWidth * 0.09 : 0,
    width: 125,
    justifyContent: "center",
    backgroundColor: "#D1EEFF",
    borderRadius: 25,
    height: 33,
  },

  centerViewV: {
    marginLeft: Platform.OS == "android" ? Sizes.ScreenWidth * 0.1 : -20,
    width: Sizes.ScreenWidth,
    // marginLeft: -80,
    // marginLeft: Constants.isIos ? -100 : 0,
    justifyContent: "center",
    width: Sizes.ScreenWidth - 180,
  },

  whitecoloredtext: {
    marginRight: 10,
    fontSize: Sizes.ExtarLarge,
    color: Colors.White_FFFFFF,
    fontWeight: "500",
  },
  smallwhitecoloredtext: {
    marginRight: 10,
    fontSize: Sizes.Small,
    color: Colors.White_FFFFFF,
    fontWeight: "500",
  },

  text: {
    // textAlign: 'flex-start',
    // width:Sizes.ScreenWidth-50,
    fontSize: Sizes.Large,
    color: Colors.White_FFFFFF,
    fontFamily: Fonts.Medium,
  },
  textMain: {
    fontSize: Sizes.Large,
    color: Colors.White_FFFFFF,
    fontWeight: "500",
  },
  menuLogoStyle: {
    height: 24,
    width: 24,
    resizeMode: "contain",
    marginLeft: 20,
  },
  notificationBlackLogoStyle: {
    height: 25.45,
    width: 25.45,
    resizeMode: "contain",
    marginLeft: 20,
  },
  notificationBellStyle: {
    height: 25,
    width: 25,
    resizeMode: "contain",
    top: 10,
    marginRight: 8,
  },
  // badgeContainer: {
  //   position: 'absolute',
  //   top: 10,
  //   right: 0,
  //   backgroundColor: 'red',
  //   borderRadius: 10,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   minWidth: 20,
  //   minHeight: 20,
  //   paddingHorizontal: 5,
  //   paddingVertical: 2,
  // },
  // badgeText: {
  //   color: 'white',
  //   fontSize: 12,
  //   fontWeight: 'bold',
  // },
  calenderLogoStyle: {
    height: 18,
    width: 18,
    resizeMode: "contain",
  },
  menuTopLogoStyle: {
    height: 22,
    width: 22,
    resizeMode: "contain",
  },
  topRightButtonView: {
    width: 90,
    height: 35,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 40,
    backgroundColor: "rgba(21, 160, 125, 0.1)",
    flexDirection: "row-reverse",
    // paddingLeft: 5,
    // paddingRight: 5,
    marginTop: 10,
  },
  backButton: {
    marginLeft: 20,
    height: 23,
    width: 23,
    // alignItems: 'flex-start',
    resizeMode: "contain",
  },
  calenderView: {
    width: 25,
    height: 25,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#15A07D",
    borderRadius: 40,
    marginRight: 10,
  },
  calenderViewUn: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    // backgroundColor: "#15A07D",
    borderRadius: 40,
    marginRight: 5,
  },
  settingButton: {
    marginLeft: 20,
    height: 24,
    width: 25,
    alignItems: "flex-start",
    resizeMode: "contain",
  },
  notificationButton: {
    marginRight: 20,
    height: 24,
    width: 25,
    alignItems: "flex-start",
    resizeMode: "contain",
  },
  backButtonOne: {
    marginLeft: 20,
    height: 50,
    width: 50,
    alignItems: "flex-start",
    resizeMode: "contain",
    marginTop: 40,
  },
  backButtonOTP: {
    marginLeft: 16,
    height: 18,
    width: 18,
    alignItems: "flex-start",
    resizeMode: "contain",
    marginRight: 10,
    marginBottom: 7,
  },
  leftView: {
    flexDirection: "row",
  },
  leftMainView: {
    // borderWidth: 1,
    // borderRadius: 40,
    // width: 40,
    // height: 40,
    // marginLeft: 12
  },
  menuView: {
    backgroundColor: "#fff",
    borderRadius: 40,
    width: 40,
    height: 40,
    shadowColor: Colors.mainColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 3,
    elevation: 5,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
  },

  otpView: {
    flexDirection: "row",
    flex: 1,
    alignItems: "center",
  },
  menuButton: {
    marginLeft: 20,
    marginRight: 0,
    height: 25,
    width: 25,
    alignItems: "flex-start",
    resizeMode: "contain",
  },
  textTitle: {
    fontSize: Sizes.Large,
    color: Colors.White_FFFFFF,
    fontFamily: Fonts.SemiBold,
  },
  blueTextTitle: {
    textAlign: "center",
    fontSize: Sizes.Medium,
    color: Colors.blueText,
    fontFamily: Fonts.Regular,
  },
  addTextBack: {
    marginLeft: Constants.isIos ? 0 : 112,
    marginBottom: 10,
  },
  addContactText: {
    color: Colors.White_FFFFFF,
    fontSize: Sizes.Regular,
    textAlign: "center",
    fontWeight: "700",
  },
  toView: {
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginLeft: 20,
    marginTop: Constants.isIos ? -35 : -50,
  },
  toText: {
    color: Colors.White_FFFFFF,
    fontSize: Sizes.Regular,
    fontWeight: "700",
  },
  keybordButton: {
    marginRight: 20,
    marginLeft: 0,
    height: 30,
    width: 30,
    resizeMode: "contain",
  },
  contactScroll: {
    marginBottom: 0,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  scrollTextBack: {
    backgroundColor: Colors.White_FFFFFF,
    borderRadius: 12,
    height: 25,
    paddingHorizontal: 10,
    marginRight: 5,
    marginTop: 5,
    display: "flex",
    justifyContent: "center",
  },
  scrollText: {
    fontSize: Sizes.Small,
    fontWeight: "400",
    color: Colors.Black_000000,
  },
  contactText: {
    fontSize: Sizes.Regular,
    flex: 1,
    flexGrow: 1,
    height: 40,
    minWidth: 40,
    textAlign: "left",
    color: Colors.White_FFFFFF,
  },
  centerViewOfContactNav: {
    height: "70%",
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    width: Sizes.ScreenWidth,
    marginLeft: Constants.isIos ? 0 : 112,
  },
  subCenterContact: {
    flex: 1,
    height: "100%",
    width: "100%",
    marginLeft: 20,
    marginRight: 20,
  },
  rightView: {
    alignItems: "center",
    flexDirection: "row",
    marginRight: 20,
    marginBottom: 15,
  },
  leftView: {
    alignItems: "flex-start",
  },
  cartStyle: {
    marginRight: 15,
    height: 22,
    width: 20,
    justifyContent: "flex-end",
    resizeMode: "contain",
  },
  backButtonVideo: {
    marginLeft: 20,
    height: 23,
    width: 23,
    // alignItems: 'flex-start',
    resizeMode: "contain",
  },
  leftViewVideo: {
    alignItems: "flex-start",
    marginRight: 20,
  },
  bellStyle: {
    height: 25,
    width: 25,
    resizeMode: "contain",
    top: 20,
    marginRight: 8,
  },
  bellcontainer: {
    position: "relative",
    padding: 10,
  },
  badgeContainer: {
    position: "absolute",
    top: -2,
    right: -2,
    backgroundColor: "red",
    justifyContent: "center",
    alignItems: "center",
    minWidth: 22,
    minHeight: 22,
    borderRadius: 11,
  },
  badgeText: {
    color: "white",
    fontSize: 10,
    fontWeight: "normal",
  },
});
